### ISSUE TITLE
Release build fails: SA1633 file-header errors in tools/python-host

### ISSUE THREAD

**Issue by JSv4** [JSv4/Docxodus#173]
## Summary

`dotnet build -c Release tools/python-host/pyhost.csproj` fails with `SA1633` file-header missing errors on `Dispatcher.cs` and `Program.cs`. The same errors reproduce on a fresh clone of `main` — this is a pre-existing main-branch defect introduced by PR #168 (which added the python-host project).

Discovered during the final verification of PR #172 (issue #163).

## Reproducer

```bash
git clone https://github.com/JSv4/Docxodus.git /tmp/docxodus-fresh
cd /tmp/docxodus-fresh
dotnet build -c Release tools/python-host/pyhost.csproj 2>&1 | tail -10
```

Expected: clean Release build.
Actual:
```
tools/python-host/Dispatcher.cs(1,1): error SA1633: The file header is missing or not located at the top of the file.
tools/python-host/Program.cs(1,1): error SA1633: The file header is missing or not located at the top of the file.
2 Error(s)
```

The `Directory.Build.props` at the repo root sets `TreatWarningsAsErrors=true` for Release, which promotes the SA1633 warnings to errors.

## Why it happens

The python-host csproj inherits the project-wide StyleCop ruleset but doesn't suppress the file-header rules (SA1633 "file must have header", SA1636 "header copyright text must match settings"). The neighboring `wasm/DocxodusWasm/DocxodusWasm.csproj` already suppresses these:

```xml
<NoWarn>$(NoWarn);SA1633;SA1636</NoWarn>
```

`pyhost.csproj` needs the same treatment.

## Fix

In `tools/python-host/pyhost.csproj`, add to the `<PropertyGroup>` containing `<TargetFramework>`:

```xml
<NoWarn>$(NoWarn);SA1633;SA1636</NoWarn>
```

(Or add the file-header text to the two `.cs` files — but that's a larger change touching code, while the suppression matches the existing convention for tooling/wasm subprojects.)

## Acceptance criteria

- [ ] `dotnet build -c Release tools/python-host/pyhost.csproj` succeeds with 0 errors on a fresh main clone.
- [ ] `dotnet build -c Release Docxodus.sln` no longer reports SA1633 errors from `tools/python-host/`. (The separate `CS1061: ImageInfo.SaveImage` errors from `Docxodus.Tests/HtmlConverterTests.cs` are a different, longstanding WASM-DLL leakage issue documented in CLAUDE.md and out of scope for this fix.)

## Related

- PR #168 — introduced the python-host project.
- PR #172 (issue #163) — surfaced this during final verification.
